package com.itss.shops.entity;
// Generated Jun 14, 2017 9:21:02 AM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import com.itss.shops.common.entity.BaseEntity;

/**
 * Ban generated by hbm2java
 */
@Entity
@Table(name = "Ban", catalog = "Coffee")
public class Ban extends BaseEntity {
	private Integer banId;
	private String maSo;
	private int trangThai;
	private Date lastUpdate;
	private Integer ghepBanBanId;
	private Integer trangThaiXoa;
	private Date thoiGianXoa;

	public Ban() {
	}

	public Ban(String maSo, int trangThai, Date lastUpdate) {
		this.maSo = maSo;
		this.trangThai = trangThai;
		this.lastUpdate = lastUpdate;
	}

	public Ban(String maSo, int trangThai, Date lastUpdate, Integer ghepBanBanId, Integer trangThaiXoa,
			Date thoiGianXoa) {
		this.maSo = maSo;
		this.trangThai = trangThai;
		this.lastUpdate = lastUpdate;
		this.ghepBanBanId = ghepBanBanId;
		this.trangThaiXoa = trangThaiXoa;
		this.thoiGianXoa = thoiGianXoa;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "BanID", unique = true, nullable = false)
	public Integer getBanId() {
		return this.banId;
	}

	public void setBanId(Integer banId) {
		this.banId = banId;
	}

	@Column(name = "MaSo", nullable = false, length = 20)
	public String getMaSo() {
		return this.maSo;
	}

	public void setMaSo(String maSo) {
		this.maSo = maSo;
	}

	@Column(name = "TrangThai", nullable = false)
	public int getTrangThai() {
		return this.trangThai;
	}

	public void setTrangThai(int trangThai) {
		this.trangThai = trangThai;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastUpdate", nullable = false, length = 19)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "GhepBan_BanID")
	public Integer getGhepBanBanId() {
		return this.ghepBanBanId;
	}

	public void setGhepBanBanId(Integer ghepBanBanId) {
		this.ghepBanBanId = ghepBanBanId;
	}

	@Column(name = "TrangThaiXoa")
	public Integer getTrangThaiXoa() {
		return this.trangThaiXoa;
	}

	public void setTrangThaiXoa(Integer trangThaiXoa) {
		this.trangThaiXoa = trangThaiXoa;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ThoiGianXoa", length = 19)
	public Date getThoiGianXoa() {
		return this.thoiGianXoa;
	}

	public void setThoiGianXoa(Date thoiGianXoa) {
		this.thoiGianXoa = thoiGianXoa;
	}
	/**
	 * 
	 */
	private static final long serialVersionUID = 2076130674766653717L;
}
