package com.itss.shops.entity;
// Generated Jun 14, 2017 9:21:02 AM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import com.itss.shops.common.entity.BaseEntity;
/**
 * ChiTietNhapHang generated by hbm2java
 */
@Entity
@Table(name = "ChiTietNhapHang", catalog = "Coffee", uniqueConstraints = @UniqueConstraint(columnNames = {
		"PhieuNhapID", "NguyenLieuID" }))
public class ChiTietNhapHang extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4178040911260512311L;
	private Integer chiTietNhapHangId;
	private int nguyenLieuId;
	private int soLuong;
	private float donGia;
	private int phieuNhapId;
	private Date lastUpdate;

	public ChiTietNhapHang() {
	}

	public ChiTietNhapHang(int nguyenLieuId, int soLuong, float donGia, int phieuNhapId, Date lastUpdate) {
		this.nguyenLieuId = nguyenLieuId;
		this.soLuong = soLuong;
		this.donGia = donGia;
		this.phieuNhapId = phieuNhapId;
		this.lastUpdate = lastUpdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ChiTietNhapHangID", unique = true, nullable = false)
	public Integer getChiTietNhapHangId() {
		return this.chiTietNhapHangId;
	}

	public void setChiTietNhapHangId(Integer chiTietNhapHangId) {
		this.chiTietNhapHangId = chiTietNhapHangId;
	}

	@Column(name = "NguyenLieuID", nullable = false)
	public int getNguyenLieuId() {
		return this.nguyenLieuId;
	}

	public void setNguyenLieuId(int nguyenLieuId) {
		this.nguyenLieuId = nguyenLieuId;
	}

	@Column(name = "SoLuong", nullable = false)
	public int getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(int soLuong) {
		this.soLuong = soLuong;
	}

	@Column(name = "DonGia", nullable = false, precision = 12, scale = 0)
	public float getDonGia() {
		return this.donGia;
	}

	public void setDonGia(float donGia) {
		this.donGia = donGia;
	}

	@Column(name = "PhieuNhapID", nullable = false)
	public int getPhieuNhapId() {
		return this.phieuNhapId;
	}

	public void setPhieuNhapId(int phieuNhapId) {
		this.phieuNhapId = phieuNhapId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LastUpdate", nullable = false, length = 10)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
