package com.itss.shops.entity;
// Generated Jun 14, 2017 9:21:02 AM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import com.itss.shops.common.entity.BaseEntity;
/**
 * ChiTietSanPham generated by hbm2java
 */
@Entity
@Table(name = "ChiTietSanPham", catalog = "Coffee", uniqueConstraints = @UniqueConstraint(columnNames = { "SanPhamID",
		"NguyenLieuID" }))
public class ChiTietSanPham extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1447497837062370526L;
	private Integer chiTietSanPhamId;
	private int sanPhamId;
	private int nguyenLieuId;
	private int soLuong;
	private Date lastUpdate;

	public ChiTietSanPham() {
	}

	public ChiTietSanPham(int sanPhamId, int nguyenLieuId, int soLuong, Date lastUpdate) {
		this.sanPhamId = sanPhamId;
		this.nguyenLieuId = nguyenLieuId;
		this.soLuong = soLuong;
		this.lastUpdate = lastUpdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ChiTietSanPhamID", unique = true, nullable = false)
	public Integer getChiTietSanPhamId() {
		return this.chiTietSanPhamId;
	}

	public void setChiTietSanPhamId(Integer chiTietSanPhamId) {
		this.chiTietSanPhamId = chiTietSanPhamId;
	}

	@Column(name = "SanPhamID", nullable = false)
	public int getSanPhamId() {
		return this.sanPhamId;
	}

	public void setSanPhamId(int sanPhamId) {
		this.sanPhamId = sanPhamId;
	}

	@Column(name = "NguyenLieuID", nullable = false)
	public int getNguyenLieuId() {
		return this.nguyenLieuId;
	}

	public void setNguyenLieuId(int nguyenLieuId) {
		this.nguyenLieuId = nguyenLieuId;
	}

	@Column(name = "SoLuong", nullable = false)
	public int getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(int soLuong) {
		this.soLuong = soLuong;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LastUpdate", nullable = false, length = 10)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
