package com.itss.shops.entity;
// Generated Jun 14, 2017 9:21:02 AM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import com.itss.shops.common.entity.BaseEntity;
/**
 * ChiTietSanPham generated by hbm2java
 */
@Entity
@Table(name = "chitiet_sanpham", uniqueConstraints = @UniqueConstraint(columnNames = { "sanpham_id",
		"nguyenlieu_id" }))
public class ChiTietSanPham extends BaseEntity {

	private Integer chiTietSanPhamId;
	private int sanPhamId;
	private int nguyenLieuId;
	private int soLuong;
	private Integer trangThaiXoa;
	private Date thoiGianXoa;

	public ChiTietSanPham() {
	}

	public ChiTietSanPham(int sanPhamId, int nguyenLieuId, int soLuong) {
		this.sanPhamId = sanPhamId;
		this.nguyenLieuId = nguyenLieuId;
		this.soLuong = soLuong;
	}

	public ChiTietSanPham(int sanPhamId, int nguyenLieuId, int soLuong, Integer trangThaiXoa,
			Date thoiGianXoa) {
		this.sanPhamId = sanPhamId;
		this.nguyenLieuId = nguyenLieuId;
		this.soLuong = soLuong;
		this.trangThaiXoa = trangThaiXoa;
		this.thoiGianXoa = thoiGianXoa;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "chitiet_sanpham_id", unique = true, nullable = false)
	public Integer getChiTietSanPhamId() {
		return this.chiTietSanPhamId;
	}

	public void setChiTietSanPhamId(Integer chiTietSanPhamId) {
		this.chiTietSanPhamId = chiTietSanPhamId;
	}

	@Column(name = "sanpham_id", nullable = false)
	public int getSanPhamId() {
		return this.sanPhamId;
	}

	public void setSanPhamId(int sanPhamId) {
		this.sanPhamId = sanPhamId;
	}

	@Column(name = "nguyenlieu_id", nullable = false)
	public int getNguyenLieuId() {
		return this.nguyenLieuId;
	}

	public void setNguyenLieuId(int nguyenLieuId) {
		this.nguyenLieuId = nguyenLieuId;
	}

	@Column(name = "soluong", nullable = false)
	public int getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(int soLuong) {
		this.soLuong = soLuong;
	}

	@Column(name = "trangthai_xoa")
	public Integer getTrangThaiXoa() {
		return this.trangThaiXoa;
	}

	public void setTrangThaiXoa(Integer trangThaiXoa) {
		this.trangThaiXoa = trangThaiXoa;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "thoigian_xoa", length = 19)
	public Date getThoiGianXoa() {
		return this.thoiGianXoa;
	}

	public void setThoiGianXoa(Date thoiGianXoa) {
		this.thoiGianXoa = thoiGianXoa;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = -1447497837062370526L;
}
