package com.itss.shops.entity;
// Generated Jun 14, 2017 9:21:02 AM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import com.itss.shops.common.entity.BaseEntity;

/**
 * ChiTietDonHang generated by hbm2java
 */
@Entity
@Table(name = "ChiTietDonHang", catalog = "Coffee", uniqueConstraints = @UniqueConstraint(columnNames = { "DonHangID",
		"SanPhamID" }))
public class ChiTietDonHang extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8767110837556002146L;
	private Integer chiTietDonHangId;
	private int sanPhamId;
	private int soLuong;
	private int donHangId;
	private Date lastUpdate;

	public ChiTietDonHang() {
	}

	public ChiTietDonHang(int sanPhamId, int soLuong, int donHangId, Date lastUpdate) {
		this.sanPhamId = sanPhamId;
		this.soLuong = soLuong;
		this.donHangId = donHangId;
		this.lastUpdate = lastUpdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ChiTietDonHangID", unique = true, nullable = false)
	public Integer getChiTietDonHangId() {
		return this.chiTietDonHangId;
	}

	public void setChiTietDonHangId(Integer chiTietDonHangId) {
		this.chiTietDonHangId = chiTietDonHangId;
	}

	@Column(name = "SanPhamID", nullable = false)
	public int getSanPhamId() {
		return this.sanPhamId;
	}

	public void setSanPhamId(int sanPhamId) {
		this.sanPhamId = sanPhamId;
	}

	@Column(name = "SoLuong", nullable = false)
	public int getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(int soLuong) {
		this.soLuong = soLuong;
	}

	@Column(name = "DonHangID", nullable = false)
	public int getDonHangId() {
		return this.donHangId;
	}

	public void setDonHangId(int donHangId) {
		this.donHangId = donHangId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LastUpdate", nullable = false, length = 10)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
