package com.itss.shops.entity;
// Generated Jun 14, 2017 9:21:02 AM by Hibernate Tools 5.2.0.CR1

import com.itss.shops.common.entity.BaseEntity;

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * ChiTietDonHang generated by hbm2java
 */
@Entity
@Table(name = "chitiet_donhang", uniqueConstraints = @UniqueConstraint(columnNames = {"donhang_id",
        "sanpham_id"}))
public class ChiTietDonHang extends BaseEntity {


    private Integer chiTietDonHangId;
    private int sanPhamId;
    private int soLuong;
    private int donHangId;
    private Integer trangThaiXoa;
    private Date thoiGianXoa;

    public ChiTietDonHang() {
    }

    public ChiTietDonHang(int sanPhamId, int soLuong, int donHangId) {
        this.sanPhamId = sanPhamId;
        this.soLuong = soLuong;
        this.donHangId = donHangId;
    }

    public ChiTietDonHang(int sanPhamId, int soLuong, int donHangId, Integer trangThaiXoa,
                          Date thoiGianXoa) {
        this.sanPhamId = sanPhamId;
        this.soLuong = soLuong;
        this.donHangId = donHangId;
        this.trangThaiXoa = trangThaiXoa;
        this.thoiGianXoa = thoiGianXoa;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "chitiet_donhang_id", unique = true, nullable = false)
    public Integer getChiTietDonHangId() {
        return this.chiTietDonHangId;
    }

    public void setChiTietDonHangId(Integer chiTietDonHangId) {
        this.chiTietDonHangId = chiTietDonHangId;
    }

    @Column(name = "sanpham_id", nullable = false)
    public int getSanPhamId() {
        return this.sanPhamId;
    }

    public void setSanPhamId(int sanPhamId) {
        this.sanPhamId = sanPhamId;
    }

    @Column(name = "soluong", nullable = false)
    public int getSoLuong() {
        return this.soLuong;
    }

    public void setSoLuong(int soLuong) {
        this.soLuong = soLuong;
    }

    @Column(name = "donhang_id", nullable = false)
    public int getDonHangId() {
        return this.donHangId;
    }

    public void setDonHangId(int donHangId) {
        this.donHangId = donHangId;
    }

    @Column(name = "trangthai_xoa")
    public Integer getTrangThaiXoa() {
        return this.trangThaiXoa;
    }

    public void setTrangThaiXoa(Integer trangThaiXoa) {
        this.trangThaiXoa = trangThaiXoa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "thoigian_xoa", length = 19)
    public Date getThoiGianXoa() {
        return this.thoiGianXoa;
    }

    public void setThoiGianXoa(Date thoiGianXoa) {
        this.thoiGianXoa = thoiGianXoa;
    }

    /**
     *
     */
    private static final long serialVersionUID = 8767110837556002146L;

}
