package com.itss.shops.entity;
// Generated Jun 14, 2017 9:21:02 AM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import com.itss.shops.common.entity.BaseEntity;
/**
 * DonHang generated by hbm2java
 */
@Entity
@Table(name = "DonHang", catalog = "Coffee")
public class DonHang extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5661907468559094787L;
	private Integer donHangId;
	private Date thoiGian;
	private float tongTien;
	private String ghiChu;
	private Date lastUpdate;
	private int banId;
	private int nhanVienId;

	public DonHang() {
	}

	public DonHang(Date thoiGian, float tongTien, String ghiChu, Date lastUpdate, int banId, int nhanVienId) {
		this.thoiGian = thoiGian;
		this.tongTien = tongTien;
		this.ghiChu = ghiChu;
		this.lastUpdate = lastUpdate;
		this.banId = banId;
		this.nhanVienId = nhanVienId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DonHangID", unique = true, nullable = false)
	public Integer getDonHangId() {
		return this.donHangId;
	}

	public void setDonHangId(Integer donHangId) {
		this.donHangId = donHangId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ThoiGian", nullable = false, length = 10)
	public Date getThoiGian() {
		return this.thoiGian;
	}

	public void setThoiGian(Date thoiGian) {
		this.thoiGian = thoiGian;
	}

	@Column(name = "TongTien", nullable = false, precision = 12, scale = 0)
	public float getTongTien() {
		return this.tongTien;
	}

	public void setTongTien(float tongTien) {
		this.tongTien = tongTien;
	}

	@Column(name = "GhiChu", nullable = false)
	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LastUpdate", nullable = false, length = 10)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "BanID", nullable = false)
	public int getBanId() {
		return this.banId;
	}

	public void setBanId(int banId) {
		this.banId = banId;
	}

	@Column(name = "NhanVienID", nullable = false)
	public int getNhanVienId() {
		return this.nhanVienId;
	}

	public void setNhanVienId(int nhanVienId) {
		this.nhanVienId = nhanVienId;
	}

}
