package com.itss.shops.entity;
// Generated Jun 14, 2017 9:21:02 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import com.itss.shops.common.entity.BaseEntity;
/**
 * KhachHang generated by hbm2java
 */
@Entity
@Table(name = "KhachHang", catalog = "Coffee")
public class KhachHang extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2453151226572611447L;
	private String maKh;
	private String tenKh;
	private String sdt;
	private String email;
	private byte gioiTinh;
	private String diaChi;
	private int diemTichLuy;
	private int congNo;
	private String status;

	public KhachHang() {
	}

	public KhachHang(String maKh, String tenKh, String sdt, String email, byte gioiTinh, String diaChi, int diemTichLuy,
			int congNo, String status) {
		this.maKh = maKh;
		this.tenKh = tenKh;
		this.sdt = sdt;
		this.email = email;
		this.gioiTinh = gioiTinh;
		this.diaChi = diaChi;
		this.diemTichLuy = diemTichLuy;
		this.congNo = congNo;
		this.status = status;
	}

	@Id

	@Column(name = "MaKH", unique = true, nullable = false)
	public String getMaKh() {
		return this.maKh;
	}

	public void setMaKh(String maKh) {
		this.maKh = maKh;
	}

	@Column(name = "TenKH", nullable = false)
	public String getTenKh() {
		return this.tenKh;
	}

	public void setTenKh(String tenKh) {
		this.tenKh = tenKh;
	}

	@Column(name = "Sdt", nullable = false, length = 11)
	public String getSdt() {
		return this.sdt;
	}

	public void setSdt(String sdt) {
		this.sdt = sdt;
	}

	@Column(name = "Email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "GioiTinh", nullable = false)
	public byte getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(byte gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Column(name = "DiaChi", nullable = false, length = 500)
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "DiemTichLuy", nullable = false)
	public int getDiemTichLuy() {
		return this.diemTichLuy;
	}

	public void setDiemTichLuy(int diemTichLuy) {
		this.diemTichLuy = diemTichLuy;
	}

	@Column(name = "CongNo", nullable = false)
	public int getCongNo() {
		return this.congNo;
	}

	public void setCongNo(int congNo) {
		this.congNo = congNo;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
