package com.itss.shops.entity;
// Generated Jun 14, 2017 9:21:02 AM by Hibernate Tools 5.2.0.CR1

import com.itss.shops.common.entity.BaseEntity;

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * KhachHang generated by hbm2java
 */
@Entity
@Table(name = "khachhang")
public class KhachHang extends BaseEntity {

    private Integer khachhangId;
    private String maKhachhang;
    private String tenKhachhang;
    private String sdt;
    private String email;
    private byte gioitinh;
    private String diachi;
    private int diemTichluy;
    private int congno;
    private int trangthai;
    private Integer trangthaiXoa;
    private Date thoigianXoa;

    public KhachHang() {
    }

    public KhachHang(String maKhachhang, String tenKhachhang, String sdt, byte gioitinh, String diachi, int diemTichluy,
                     int congno, int trangthai) {
        this.maKhachhang = maKhachhang;
        this.tenKhachhang = tenKhachhang;
        this.sdt = sdt;
        this.gioitinh = gioitinh;
        this.diachi = diachi;
        this.diemTichluy = diemTichluy;
        this.congno = congno;
        this.trangthai = trangthai;
    }

    public KhachHang(String maKhachhang, String tenKhachhang, String sdt, String email, byte gioitinh, String diachi,
                     int diemTichluy, int congno, int trangthai, Integer trangthaiXoa, Date thoigianXoa) {
        this.maKhachhang = maKhachhang;
        this.tenKhachhang = tenKhachhang;
        this.sdt = sdt;
        this.email = email;
        this.gioitinh = gioitinh;
        this.diachi = diachi;
        this.diemTichluy = diemTichluy;
        this.congno = congno;
        this.trangthai = trangthai;
        this.trangthaiXoa = trangthaiXoa;
        this.thoigianXoa = thoigianXoa;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "khachhang_id", unique = true, nullable = false)
    public Integer getKhachhangId() {
        return this.khachhangId;
    }

    public void setKhachhangId(Integer khachhangId) {
        this.khachhangId = khachhangId;
    }

    @Column(name = "ma_khachhang", nullable = false)
    public String getMaKhachhang() {
        return this.maKhachhang;
    }

    public void setMaKhachhang(String maKhachhang) {
        this.maKhachhang = maKhachhang;
    }

    @Column(name = "ten_khachhang", nullable = false)
    public String getTenKhachhang() {
        return this.tenKhachhang;
    }

    public void setTenKhachhang(String tenKhachhang) {
        this.tenKhachhang = tenKhachhang;
    }

    @Column(name = "sdt", nullable = false, length = 11)
    public String getSdt() {
        return this.sdt;
    }

    public void setSdt(String sdt) {
        this.sdt = sdt;
    }

    @Column(name = "email")
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "gioitinh", nullable = false)
    public byte getGioitinh() {
        return this.gioitinh;
    }

    public void setGioitinh(byte gioitinh) {
        this.gioitinh = gioitinh;
    }

    @Column(name = "diachi", nullable = false, length = 500)
    public String getDiachi() {
        return this.diachi;
    }

    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }

    @Column(name = "diem_tichluy", nullable = false)
    public int getDiemTichluy() {
        return this.diemTichluy;
    }

    public void setDiemTichluy(int diemTichluy) {
        this.diemTichluy = diemTichluy;
    }

    @Column(name = "congno", nullable = false)
    public int getCongno() {
        return this.congno;
    }

    public void setCongno(int congno) {
        this.congno = congno;
    }

    @Column(name = "trangthai", nullable = false)
    public int getTrangthai() {
        return this.trangthai;
    }

    public void setTrangthai(int trangthai) {
        this.trangthai = trangthai;
    }

    @Column(name = "trangthai_xoa")
    public Integer getTrangthaiXoa() {
        return this.trangthaiXoa;
    }

    public void setTrangthaiXoa(Integer trangthaiXoa) {
        this.trangthaiXoa = trangthaiXoa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "thoigian_xoa", length = 19)
    public Date getThoigianXoa() {
        return this.thoigianXoa;
    }

    public void setThoigianXoa(Date thoigianXoa) {
        this.thoigianXoa = thoigianXoa;
    }

    /**
     *
     */
    private static final long serialVersionUID = -2453151226572611447L;
}
