package com.itss.shops.entity;
// Generated Jun 14, 2017 9:21:02 AM by Hibernate Tools 5.2.0.CR1

import com.itss.shops.common.entity.BaseEntity;

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * KhuyenMai generated by hbm2java
 */
@Entity
@Table(name = "khuyenmai")
public class KhuyenMai extends BaseEntity {

    private Integer khuyenMaiId;
    private Date thoiGianBatDau;
    private Date thoiGianKetThuc;
    private int loaiKhuyenMai;
    private int doiTuongId;
    private String maKhuyenMai;
    private float giaTriPhanTram;
    private float giaTriCoDinh;
    private String moTa;
    private Integer trangThaiXoa;
    private Date thoiGianXoa;

    public KhuyenMai() {
    }

    public KhuyenMai(Date thoiGianBatDau, Date thoiGianKetThuc, int loaiKhuyenMai, int doiTuongId, String maKhuyenMai,
                     float giaTriPhanTram, float giaTriCoDinh, String moTa) {
        this.thoiGianBatDau = thoiGianBatDau;
        this.thoiGianKetThuc = thoiGianKetThuc;
        this.loaiKhuyenMai = loaiKhuyenMai;
        this.doiTuongId = doiTuongId;
        this.maKhuyenMai = maKhuyenMai;
        this.giaTriPhanTram = giaTriPhanTram;
        this.giaTriCoDinh = giaTriCoDinh;
        this.moTa = moTa;
    }

    public KhuyenMai(Date thoiGianBatDau, Date thoiGianKetThuc, int loaiKhuyenMai, int doiTuongId, String maKhuyenMai,
                     float giaTriPhanTram, float giaTriCoDinh, String moTa, Integer trangThaiXoa,
                     Date thoiGianXoa) {
        this.thoiGianBatDau = thoiGianBatDau;
        this.thoiGianKetThuc = thoiGianKetThuc;
        this.loaiKhuyenMai = loaiKhuyenMai;
        this.doiTuongId = doiTuongId;
        this.maKhuyenMai = maKhuyenMai;
        this.giaTriPhanTram = giaTriPhanTram;
        this.giaTriCoDinh = giaTriCoDinh;
        this.moTa = moTa;
        this.trangThaiXoa = trangThaiXoa;
        this.thoiGianXoa = thoiGianXoa;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "khuyenmai_id", unique = true, nullable = false)
    public Integer getKhuyenMaiId() {
        return this.khuyenMaiId;
    }

    public void setKhuyenMaiId(Integer khuyenMaiId) {
        this.khuyenMaiId = khuyenMaiId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "thoigian_batdau", nullable = false, length = 19)
    public Date getThoiGianBatDau() {
        return this.thoiGianBatDau;
    }

    public void setThoiGianBatDau(Date thoiGianBatDau) {
        this.thoiGianBatDau = thoiGianBatDau;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "thoigian_ketthuc", nullable = false, length = 19)
    public Date getThoiGianKetThuc() {
        return this.thoiGianKetThuc;
    }

    public void setThoiGianKetThuc(Date thoiGianKetThuc) {
        this.thoiGianKetThuc = thoiGianKetThuc;
    }

    @Column(name = "loai_khuyenmai", nullable = false)
    public int getLoaiKhuyenMai() {
        return this.loaiKhuyenMai;
    }

    public void setLoaiKhuyenMai(int loaiKhuyenMai) {
        this.loaiKhuyenMai = loaiKhuyenMai;
    }

    @Column(name = "doituong_id", nullable = false)
    public int getDoiTuongId() {
        return this.doiTuongId;
    }

    public void setDoiTuongId(int doiTuongId) {
        this.doiTuongId = doiTuongId;
    }

    @Column(name = "ma_khuyenmai", nullable = false, length = 20)
    public String getMaKhuyenMai() {
        return this.maKhuyenMai;
    }

    public void setMaKhuyenMai(String maKhuyenMai) {
        this.maKhuyenMai = maKhuyenMai;
    }

    @Column(name = "giatri_phantram", nullable = false, precision = 12, scale = 0)
    public float getGiaTriPhanTram() {
        return this.giaTriPhanTram;
    }

    public void setGiaTriPhanTram(float giaTriPhanTram) {
        this.giaTriPhanTram = giaTriPhanTram;
    }

    @Column(name = "giatri_codinh", nullable = false, precision = 12, scale = 0)
    public float getGiaTriCoDinh() {
        return this.giaTriCoDinh;
    }

    public void setGiaTriCoDinh(float giaTriCoDinh) {
        this.giaTriCoDinh = giaTriCoDinh;
    }

    @Column(name = "mota", nullable = false)
    public String getMoTa() {
        return this.moTa;
    }

    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }

    @Column(name = "trangthai_xoa")
    public Integer getTrangThaiXoa() {
        return this.trangThaiXoa;
    }

    public void setTrangThaiXoa(Integer trangThaiXoa) {
        this.trangThaiXoa = trangThaiXoa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "thoigian_xoa", length = 19)
    public Date getThoiGianXoa() {
        return this.thoiGianXoa;
    }

    public void setThoiGianXoa(Date thoiGianXoa) {
        this.thoiGianXoa = thoiGianXoa;
    }

    /**
     *
     */
    private static final long serialVersionUID = 8484010285881911525L;
}
