package com.itss.shops.entity;
// Generated Jun 14, 2017 9:21:02 AM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import com.itss.shops.common.entity.BaseEntity;
/**
 * KhuyenMai generated by hbm2java
 */
@Entity
@Table(name = "KhuyenMai", catalog = "Coffee")
public class KhuyenMai extends BaseEntity {

	private Integer khuyenMaiId;
	private Date thoiGianBatDau;
	private Date thoiGianKetThuc;
	private int loaiKhuyenMai;
	private int doiTuongId;
	private String maKhuyenMai;
	private float giaTriPhanTram;
	private float giaTriCoDinh;
	private String moTa;
	private Date lastUpdate;
	private Integer trangThaiXoa;
	private Date thoiGianXoa;

	public KhuyenMai() {
	}

	public KhuyenMai(Date thoiGianBatDau, Date thoiGianKetThuc, int loaiKhuyenMai, int doiTuongId, String maKhuyenMai,
			float giaTriPhanTram, float giaTriCoDinh, String moTa, Date lastUpdate) {
		this.thoiGianBatDau = thoiGianBatDau;
		this.thoiGianKetThuc = thoiGianKetThuc;
		this.loaiKhuyenMai = loaiKhuyenMai;
		this.doiTuongId = doiTuongId;
		this.maKhuyenMai = maKhuyenMai;
		this.giaTriPhanTram = giaTriPhanTram;
		this.giaTriCoDinh = giaTriCoDinh;
		this.moTa = moTa;
		this.lastUpdate = lastUpdate;
	}

	public KhuyenMai(Date thoiGianBatDau, Date thoiGianKetThuc, int loaiKhuyenMai, int doiTuongId, String maKhuyenMai,
			float giaTriPhanTram, float giaTriCoDinh, String moTa, Date lastUpdate, Integer trangThaiXoa,
			Date thoiGianXoa) {
		this.thoiGianBatDau = thoiGianBatDau;
		this.thoiGianKetThuc = thoiGianKetThuc;
		this.loaiKhuyenMai = loaiKhuyenMai;
		this.doiTuongId = doiTuongId;
		this.maKhuyenMai = maKhuyenMai;
		this.giaTriPhanTram = giaTriPhanTram;
		this.giaTriCoDinh = giaTriCoDinh;
		this.moTa = moTa;
		this.lastUpdate = lastUpdate;
		this.trangThaiXoa = trangThaiXoa;
		this.thoiGianXoa = thoiGianXoa;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "KhuyenMaiID", unique = true, nullable = false)
	public Integer getKhuyenMaiId() {
		return this.khuyenMaiId;
	}

	public void setKhuyenMaiId(Integer khuyenMaiId) {
		this.khuyenMaiId = khuyenMaiId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ThoiGianBatDau", nullable = false, length = 19)
	public Date getThoiGianBatDau() {
		return this.thoiGianBatDau;
	}

	public void setThoiGianBatDau(Date thoiGianBatDau) {
		this.thoiGianBatDau = thoiGianBatDau;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ThoiGianKetThuc", nullable = false, length = 19)
	public Date getThoiGianKetThuc() {
		return this.thoiGianKetThuc;
	}

	public void setThoiGianKetThuc(Date thoiGianKetThuc) {
		this.thoiGianKetThuc = thoiGianKetThuc;
	}

	@Column(name = "LoaiKhuyenMai", nullable = false)
	public int getLoaiKhuyenMai() {
		return this.loaiKhuyenMai;
	}

	public void setLoaiKhuyenMai(int loaiKhuyenMai) {
		this.loaiKhuyenMai = loaiKhuyenMai;
	}

	@Column(name = "DoiTuongID", nullable = false)
	public int getDoiTuongId() {
		return this.doiTuongId;
	}

	public void setDoiTuongId(int doiTuongId) {
		this.doiTuongId = doiTuongId;
	}

	@Column(name = "MaKhuyenMai", nullable = false, length = 20)
	public String getMaKhuyenMai() {
		return this.maKhuyenMai;
	}

	public void setMaKhuyenMai(String maKhuyenMai) {
		this.maKhuyenMai = maKhuyenMai;
	}

	@Column(name = "GiaTriPhanTram", nullable = false, precision = 12, scale = 0)
	public float getGiaTriPhanTram() {
		return this.giaTriPhanTram;
	}

	public void setGiaTriPhanTram(float giaTriPhanTram) {
		this.giaTriPhanTram = giaTriPhanTram;
	}

	@Column(name = "GiaTriCoDinh", nullable = false, precision = 12, scale = 0)
	public float getGiaTriCoDinh() {
		return this.giaTriCoDinh;
	}

	public void setGiaTriCoDinh(float giaTriCoDinh) {
		this.giaTriCoDinh = giaTriCoDinh;
	}

	@Column(name = "MoTa", nullable = false)
	public String getMoTa() {
		return this.moTa;
	}

	public void setMoTa(String moTa) {
		this.moTa = moTa;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastUpdate", nullable = false, length = 19)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "TrangThaiXoa")
	public Integer getTrangThaiXoa() {
		return this.trangThaiXoa;
	}

	public void setTrangThaiXoa(Integer trangThaiXoa) {
		this.trangThaiXoa = trangThaiXoa;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ThoiGianXoa", length = 19)
	public Date getThoiGianXoa() {
		return this.thoiGianXoa;
	}

	public void setThoiGianXoa(Date thoiGianXoa) {
		this.thoiGianXoa = thoiGianXoa;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 8484010285881911525L;
}
