package com.itss.shops.entity;
// Generated Jun 14, 2017 9:21:02 AM by Hibernate Tools 5.2.0.CR1

import com.itss.shops.common.entity.BaseEntity;

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * NguyenLieu generated by hbm2java
 */
@Entity
@Table(name = "nguyenlieu")
public class NguyenLieu extends BaseEntity {

    private Integer nguyenLieuId;
    private int soLuong;
    private String donVi;
    private String ten;
    private Integer trangThaiXoa;
    private Date thoiGianXoa;

    public NguyenLieu() {
    }

    public NguyenLieu(int soLuong, String donVi, String ten) {
        this.soLuong = soLuong;
        this.donVi = donVi;
        this.ten = ten;
    }

    public NguyenLieu(int soLuong, String donVi, String ten, Integer trangThaiXoa, Date thoiGianXoa) {
        this.soLuong = soLuong;
        this.donVi = donVi;
        this.ten = ten;
        this.trangThaiXoa = trangThaiXoa;
        this.thoiGianXoa = thoiGianXoa;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "nguyenlieu_id", unique = true, nullable = false)
    public Integer getNguyenLieuId() {
        return this.nguyenLieuId;
    }

    public void setNguyenLieuId(Integer nguyenLieuId) {
        this.nguyenLieuId = nguyenLieuId;
    }

    @Column(name = "soluong", nullable = false)
    public int getSoLuong() {
        return this.soLuong;
    }

    public void setSoLuong(int soLuong) {
        this.soLuong = soLuong;
    }

    @Column(name = "donvi", nullable = false, length = 50)
    public String getDonVi() {
        return this.donVi;
    }

    public void setDonVi(String donVi) {
        this.donVi = donVi;
    }

    @Column(name = "ten_nguyenlieu", nullable = false)
    public String getTen() {
        return this.ten;
    }

    public void setTen(String ten) {
        this.ten = ten;
    }

    @Column(name = "trangthai_xoa")
    public Integer getTrangThaiXoa() {
        return this.trangThaiXoa;
    }

    public void setTrangThaiXoa(Integer trangThaiXoa) {
        this.trangThaiXoa = trangThaiXoa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "thoigian_xoa", length = 19)
    public Date getThoiGianXoa() {
        return this.thoiGianXoa;
    }

    public void setThoiGianXoa(Date thoiGianXoa) {
        this.thoiGianXoa = thoiGianXoa;
    }

    /**
     *
     */
    private static final long serialVersionUID = -2584815483708580448L;
}
