package com.itss.shops.entity;
// Generated Jun 14, 2017 9:21:02 AM by Hibernate Tools 5.2.0.CR1

import com.itss.shops.common.entity.BaseEntity;

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * NhanVien generated by hbm2java
 */
@Entity
@Table(name = "nhanvien")
public class NhanVien extends BaseEntity {

    private Integer nhanVienId;
    private String hoTen;
    private Date ngaySinh;
    private String cmnd;
    private String sdt;
    private Integer trangThaiXoa;
    private Date thoiGianXoa;

    public NhanVien() {
    }

    public NhanVien(String hoTen, Date ngaySinh, String cmnd, String sdt) {
        this.hoTen = hoTen;
        this.ngaySinh = ngaySinh;
        this.cmnd = cmnd;
        this.sdt = sdt;
    }

    public NhanVien(String hoTen, Date ngaySinh, String cmnd, String sdt, Integer trangThaiXoa,
                    Date thoiGianXoa) {
        this.hoTen = hoTen;
        this.ngaySinh = ngaySinh;
        this.cmnd = cmnd;
        this.sdt = sdt;
        this.trangThaiXoa = trangThaiXoa;
        this.thoiGianXoa = thoiGianXoa;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "nhanvien_id", unique = true, nullable = false)
    public Integer getNhanVienId() {
        return this.nhanVienId;
    }

    public void setNhanVienId(Integer nhanVienId) {
        this.nhanVienId = nhanVienId;
    }

    @Column(name = "hoten", nullable = false, length = 50)
    public String getHoTen() {
        return this.hoTen;
    }

    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ngaysinh", nullable = false, length = 19)
    public Date getNgaySinh() {
        return this.ngaySinh;
    }

    public void setNgaySinh(Date ngaySinh) {
        this.ngaySinh = ngaySinh;
    }

    @Column(name = "cmnd", nullable = false, length = 20)
    public String getCmnd() {
        return this.cmnd;
    }

    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }

    @Column(name = "sdt", nullable = false, length = 20)
    public String getSdt() {
        return this.sdt;
    }

    public void setSdt(String sdt) {
        this.sdt = sdt;
    }

    @Column(name = "trangthai_xoa")
    public Integer getTrangThaiXoa() {
        return this.trangThaiXoa;
    }

    public void setTrangThaiXoa(Integer trangThaiXoa) {
        this.trangThaiXoa = trangThaiXoa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "thoigian_xoa", length = 19)
    public Date getThoiGianXoa() {
        return this.thoiGianXoa;
    }

    public void setThoiGianXoa(Date thoiGianXoa) {
        this.thoiGianXoa = thoiGianXoa;
    }

    /**
     *
     */
    private static final long serialVersionUID = 8267640856242370630L;
}
