package com.itss.shops.entity;
// Generated Jun 14, 2017 9:21:02 AM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import com.itss.shops.common.entity.BaseEntity;
/**
 * NhanVien generated by hbm2java
 */
@Entity
@Table(name = "NhanVien", catalog = "Coffee")
public class NhanVien extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8267640856242370630L;
	private Integer nhanVienId;
	private String hoTen;
	private Date ngaySinh;
	private String cmnd;
	private String sdt;
	private Date lastUpdate;

	public NhanVien() {
	}

	public NhanVien(String hoTen, Date ngaySinh, String cmnd, String sdt, Date lastUpdate) {
		this.hoTen = hoTen;
		this.ngaySinh = ngaySinh;
		this.cmnd = cmnd;
		this.sdt = sdt;
		this.lastUpdate = lastUpdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "NhanVienID", unique = true, nullable = false)
	public Integer getNhanVienId() {
		return this.nhanVienId;
	}

	public void setNhanVienId(Integer nhanVienId) {
		this.nhanVienId = nhanVienId;
	}

	@Column(name = "HoTen", nullable = false, length = 50)
	public String getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgaySinh", nullable = false, length = 10)
	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	@Column(name = "CMND", nullable = false, length = 20)
	public String getCmnd() {
		return this.cmnd;
	}

	public void setCmnd(String cmnd) {
		this.cmnd = cmnd;
	}

	@Column(name = "SDT", nullable = false, length = 20)
	public String getSdt() {
		return this.sdt;
	}

	public void setSdt(String sdt) {
		this.sdt = sdt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LastUpdate", nullable = false, length = 10)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
