package com.itss.shops.entity;
// Generated Jun 14, 2017 9:21:02 AM by Hibernate Tools 5.2.0.CR1

import com.itss.shops.common.entity.BaseEntity;

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * NhomSanPham generated by hbm2java
 */
@Entity
@Table(name = "nhom_sanpham")
public class NhomSanPham extends BaseEntity {

    private Integer nhomSanPhamId;
    private String hinhAnh;
    private String tenNhom;
    private String moTa;
    private boolean hienThi;
    private Integer trangThaiXoa;
    private Date thoiGianXoa;

    public NhomSanPham() {
    }

    public NhomSanPham(String tenNhom, String moTa, boolean hienThi) {
        this.tenNhom = tenNhom;
        this.moTa = moTa;
        this.hienThi = hienThi;
    }

    public NhomSanPham(String hinhAnh, String tenNhom, String moTa, boolean hienThi,
                       Integer trangThaiXoa, Date thoiGianXoa) {
        this.hinhAnh = hinhAnh;
        this.tenNhom = tenNhom;
        this.moTa = moTa;
        this.hienThi = hienThi;
        this.trangThaiXoa = trangThaiXoa;
        this.thoiGianXoa = thoiGianXoa;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "nhom_sanpham_id", unique = true, nullable = false)
    public Integer getNhomSanPhamId() {
        return this.nhomSanPhamId;
    }

    public void setNhomSanPhamId(Integer nhomSanPhamId) {
        this.nhomSanPhamId = nhomSanPhamId;
    }

    @Column(name = "hinhanh")
    public String getHinhAnh() {
        return this.hinhAnh;
    }

    public void setHinhAnh(String hinhAnh) {
        this.hinhAnh = hinhAnh;
    }

    @Column(name = "ten_nhom", nullable = false)
    public String getTenNhom() {
        return this.tenNhom;
    }

    public void setTenNhom(String tenNhom) {
        this.tenNhom = tenNhom;
    }

    @Column(name = "mota", nullable = false)
    public String getMoTa() {
        return this.moTa;
    }

    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }

    @Column(name = "hienthi", nullable = false)
    public boolean isHienThi() {
        return this.hienThi;
    }

    public void setHienThi(boolean hienThi) {
        this.hienThi = hienThi;
    }

    @Column(name = "trangthai_xoa")
    public Integer getTrangThaiXoa() {
        return this.trangThaiXoa;
    }

    public void setTrangThaiXoa(Integer trangThaiXoa) {
        this.trangThaiXoa = trangThaiXoa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "thoigian_xoa", length = 19)
    public Date getThoiGianXoa() {
        return this.thoiGianXoa;
    }

    public void setThoiGianXoa(Date thoiGianXoa) {
        this.thoiGianXoa = thoiGianXoa;
    }

    /**
     *
     */
    private static final long serialVersionUID = 7572465635351838981L;
}
