package com.itss.shops.entity;
// Generated Jun 14, 2017 9:21:02 AM by Hibernate Tools 5.2.0.CR1

import com.itss.shops.common.entity.BaseEntity;

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * PhieuNhap generated by hbm2java
 */
@Entity
@Table(name = "phieunhap")
public class PhieuNhap extends BaseEntity {

    private Integer phieuNhapId;
    private Date ngayNhap;
    private float tongGiaTri;
    private int nhanVienId;
    private Integer trangThaiXoa;
    private Date thoiGianXoa;

    public PhieuNhap() {
    }

    public PhieuNhap(Date ngayNhap, float tongGiaTri, int nhanVienId) {
        this.ngayNhap = ngayNhap;
        this.tongGiaTri = tongGiaTri;
        this.nhanVienId = nhanVienId;
    }

    public PhieuNhap(Date ngayNhap, float tongGiaTri, int nhanVienId, Integer trangThaiXoa,
                     Date thoiGianXoa) {
        this.ngayNhap = ngayNhap;
        this.tongGiaTri = tongGiaTri;
        this.nhanVienId = nhanVienId;
        this.trangThaiXoa = trangThaiXoa;
        this.thoiGianXoa = thoiGianXoa;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "phieunhap_id", unique = true, nullable = false)
    public Integer getPhieuNhapId() {
        return this.phieuNhapId;
    }

    public void setPhieuNhapId(Integer phieuNhapId) {
        this.phieuNhapId = phieuNhapId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "ngaynhap", nullable = false, length = 10)
    public Date getNgayNhap() {
        return this.ngayNhap;
    }

    public void setNgayNhap(Date ngayNhap) {
        this.ngayNhap = ngayNhap;
    }

    @Column(name = "tong_giatri", nullable = false, precision = 12, scale = 0)
    public float getTongGiaTri() {
        return this.tongGiaTri;
    }

    public void setTongGiaTri(float tongGiaTri) {
        this.tongGiaTri = tongGiaTri;
    }

    @Column(name = "nhanvien_id", nullable = false)
    public int getNhanVienId() {
        return this.nhanVienId;
    }

    public void setNhanVienId(int nhanVienId) {
        this.nhanVienId = nhanVienId;
    }

    @Column(name = "trangthai_xoa")
    public Integer getTrangThaiXoa() {
        return this.trangThaiXoa;
    }

    public void setTrangThaiXoa(Integer trangThaiXoa) {
        this.trangThaiXoa = trangThaiXoa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "thoigian_xoa", length = 19)
    public Date getThoiGianXoa() {
        return this.thoiGianXoa;
    }

    public void setThoiGianXoa(Date thoiGianXoa) {
        this.thoiGianXoa = thoiGianXoa;
    }

    /**
     *
     */
    private static final long serialVersionUID = -6774697966635344979L;
}
