package com.itss.shops.entity;
// Generated Jun 14, 2017 9:21:02 AM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import com.itss.shops.common.entity.BaseEntity;
/**
 * PhieuNhap generated by hbm2java
 */
@Entity
@Table(name = "PhieuNhap", catalog = "Coffee")
public class PhieuNhap extends BaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6774697966635344979L;
	private Integer phieuNhapId;
	private Date ngayNhap;
	private float tongGiaTri;
	private Date lastUpdate;
	private int nhanVienId;

	public PhieuNhap() {
	}

	public PhieuNhap(Date ngayNhap, float tongGiaTri, Date lastUpdate, int nhanVienId) {
		this.ngayNhap = ngayNhap;
		this.tongGiaTri = tongGiaTri;
		this.lastUpdate = lastUpdate;
		this.nhanVienId = nhanVienId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PhieuNhapID", unique = true, nullable = false)
	public Integer getPhieuNhapId() {
		return this.phieuNhapId;
	}

	public void setPhieuNhapId(Integer phieuNhapId) {
		this.phieuNhapId = phieuNhapId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgayNhap", nullable = false, length = 10)
	public Date getNgayNhap() {
		return this.ngayNhap;
	}

	public void setNgayNhap(Date ngayNhap) {
		this.ngayNhap = ngayNhap;
	}

	@Column(name = "TongGiaTri", nullable = false, precision = 12, scale = 0)
	public float getTongGiaTri() {
		return this.tongGiaTri;
	}

	public void setTongGiaTri(float tongGiaTri) {
		this.tongGiaTri = tongGiaTri;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LastUpdate", nullable = false, length = 10)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "NhanVienID", nullable = false)
	public int getNhanVienId() {
		return this.nhanVienId;
	}

	public void setNhanVienId(int nhanVienId) {
		this.nhanVienId = nhanVienId;
	}

}
