package com.itss.shops.entity;
// Generated Jun 14, 2017 9:21:02 AM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import com.itss.shops.common.entity.BaseEntity;
/**
 * SanPham generated by hbm2java
 */
@Entity
@Table(name = "SanPham", catalog = "Coffee")
public class SanPham extends BaseEntity {

	private Integer sanPhamId;
	private Integer nhomSanPhamId;
	private float donGia;
	private int moTa;
	private String hinhAnh;
	private boolean hienThi;
	private Date lastUpdate;
	private Integer trangThaiXoa;
	private Date thoiGianXoa;

	public SanPham() {
	}

	public SanPham(float donGia, int moTa, boolean hienThi, Date lastUpdate) {
		this.donGia = donGia;
		this.moTa = moTa;
		this.hienThi = hienThi;
		this.lastUpdate = lastUpdate;
	}

	public SanPham(Integer nhomSanPhamId, float donGia, int moTa, String hinhAnh, boolean hienThi, Date lastUpdate,
			Integer trangThaiXoa, Date thoiGianXoa) {
		this.nhomSanPhamId = nhomSanPhamId;
		this.donGia = donGia;
		this.moTa = moTa;
		this.hinhAnh = hinhAnh;
		this.hienThi = hienThi;
		this.lastUpdate = lastUpdate;
		this.trangThaiXoa = trangThaiXoa;
		this.thoiGianXoa = thoiGianXoa;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SanPhamID", unique = true, nullable = false)
	public Integer getSanPhamId() {
		return this.sanPhamId;
	}

	public void setSanPhamId(Integer sanPhamId) {
		this.sanPhamId = sanPhamId;
	}

	@Column(name = "NhomSanPhamID")
	public Integer getNhomSanPhamId() {
		return this.nhomSanPhamId;
	}

	public void setNhomSanPhamId(Integer nhomSanPhamId) {
		this.nhomSanPhamId = nhomSanPhamId;
	}

	@Column(name = "DonGia", nullable = false, precision = 12, scale = 0)
	public float getDonGia() {
		return this.donGia;
	}

	public void setDonGia(float donGia) {
		this.donGia = donGia;
	}

	@Column(name = "MoTa", nullable = false)
	public int getMoTa() {
		return this.moTa;
	}

	public void setMoTa(int moTa) {
		this.moTa = moTa;
	}

	@Column(name = "HinhAnh")
	public String getHinhAnh() {
		return this.hinhAnh;
	}

	public void setHinhAnh(String hinhAnh) {
		this.hinhAnh = hinhAnh;
	}

	@Column(name = "HienThi", nullable = false)
	public boolean isHienThi() {
		return this.hienThi;
	}

	public void setHienThi(boolean hienThi) {
		this.hienThi = hienThi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastUpdate", nullable = false, length = 19)
	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "TrangThaiXoa")
	public Integer getTrangThaiXoa() {
		return this.trangThaiXoa;
	}

	public void setTrangThaiXoa(Integer trangThaiXoa) {
		this.trangThaiXoa = trangThaiXoa;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ThoiGianXoa", length = 19)
	public Date getThoiGianXoa() {
		return this.thoiGianXoa;
	}

	public void setThoiGianXoa(Date thoiGianXoa) {
		this.thoiGianXoa = thoiGianXoa;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = -7886060395269347557L;
}
